excel_file: 'class.xlsx'
class: 'site'
syllabus_message: 'You should always look to this website for the most recent updates.\n\nAn initial version of the syllabus can be found below. \n\n'
bc_class_header: '\nThe following materials will be covered during the class session.\n'
in_class_header: '\nPlease review following materials before the class session.\n'
assignments_header: '\nAll assignments should be submitted to the LMS at 11:59 PM on the date indicated.\n'
schedule_header: "\nPlease check here for the latest course schedule of activities.\n"
website_url: qm.analyticsdojo.com